### ISSUE TITLE
Frontend: Leaderboard Page - Create mockup

### ISSUE THREAD

**Issue by nclskfm** [nclskfm/square-core#13]
Create a mockup and send to Haritz for feedback (available via discord during vacations).
User selects a dataset => show all evaluation-results on that dataset with default-metric. User can then also select a different metric (but default is always the default-metric of the dataset).

**Examples:**
https://rajpurkar.github.io/SQuAD-explorer/
https://hotpotqa.github.io/index.html
https://huggingface.co/spaces/autoevaluate/leaderboards

**Comment by BenediktStuhrmann** [comment]
For table maybe use datatables?
Docs: https://datatables.net/blog/2022-06-22-vue
Demo: https://stackblitz.com/edit/datatables-net-vue3-bootstrap5?file=src%2FApp.vue

**Comment by BenediktStuhrmann** [comment]
![Image](https://user-images.githubusercontent.com/22676519/210547791-d00e17af-91c0-47b9-b067-d829c758a231.png)
