### ISSUE TITLE
Implement dataset endpoint

### ISSUE THREAD

**Issue by nclskfm** [nclskfm/square-core#7]
Create a new endpoint `/dataset` in the evaluator. (Admin endpoint; called manually; no UI required for now).
For now we only need support for `extractive-QA`. However keep in mind, that different skill-types might require a different mapping.

```json
{
  "name":"squad", <= String (Primary Key? (should be unique))
  "skill-type":"extractive-qa", <= SkillType
  "mapping":{ <= some kind of mapping object
    "id-column":"id", <= String
    "question-column":"questions", <= String
    "context-column":"context", <= String
    "answer-column":"answers" <= String
  }
}
```

Maybe versioning?

 - [ ] `POST /dataset` takes the above data and save it to the database.
 - [ ] `PUT /dataset/{dataset-pk}` takes the above data and updates an existing entry by its PK
 - [ ] `DELETE /dataset/{dataset-pk}` deletes an existing entry by its PK
 - [ ] `GET /dataset/{dataset-pk}` retrieves an existing entry by its PK

When a dataset is created/updated/deleted make sure to also call the dataset_handler to trigger download/deletion respectively.

**Comment by BenediktStuhrmann** [comment]
```json
{
  "name":"quoref",
  "skill-type":"extractive-qa",
  "metric":"squad",
  "mapping":{
    "id-column":"id",
    "question-column":"question",
    "context-column":"context",
    "answer-text-column":"answers.text",
    "answer-start-column":"answers.answer_start"
  }
}
```

```json
{
  "name":"commonsense_qa",
  "skill-type":"multiple-choice",
  "metric":"accuracy",
  "mapping":{
    "id-column":"id",
    "question-column":"question",
    "choices-columns":[
      "choices.text"
    ],
    "choices-key-mapping-column":"choices.label",
    "answer-index-column":"answerKey"
  }
}
```
